//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektAspNetStudia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjektAspNetStudia.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CreateNewRoomModalCloseButtonText {
            get {
                return ResourceManager.GetString("CreateNewRoomModalCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateNewRoomModalCreateButtonText {
            get {
                return ResourceManager.GetString("CreateNewRoomModalCreateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room name:.
        /// </summary>
        public static string CreateNewRoomModalRoomNameLabel {
            get {
                return ResourceManager.GetString("CreateNewRoomModalRoomNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for users:.
        /// </summary>
        public static string CreateNewRoomModalSearchForUsersLabel {
            get {
                return ResourceManager.GetString("CreateNewRoomModalSearchForUsersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected users:.
        /// </summary>
        public static string CreateNewRoomModalSelectedUsersLabel {
            get {
                return ResourceManager.GetString("CreateNewRoomModalSelectedUsersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Room.
        /// </summary>
        public static string CreateNewRoomModalTitle {
            get {
                return ResourceManager.GetString("CreateNewRoomModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address is required..
        /// </summary>
        public static string LoginFormEmailRequired {
            get {
                return ResourceManager.GetString("LoginFormEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string LoginFormLoginLabel {
            get {
                return ResourceManager.GetString("LoginFormLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username....
        /// </summary>
        public static string LoginFormLoginPlaceholder {
            get {
                return ResourceManager.GetString("LoginFormLoginPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LoginFormPasswordLabel {
            get {
                return ResourceManager.GetString("LoginFormPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password....
        /// </summary>
        public static string LoginFormPasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginFormPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string LoginFormPasswordRequired {
            get {
                return ResourceManager.GetString("LoginFormPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LoginFormRegisterHyperlink {
            get {
                return ResourceManager.GetString("LoginFormRegisterHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have account?.
        /// </summary>
        public static string LoginFormRegisterQuestion {
            get {
                return ResourceManager.GetString("LoginFormRegisterQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LoginFormSubmitButton {
            get {
                return ResourceManager.GetString("LoginFormSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats.
        /// </summary>
        public static string RecentChatTitleLabel {
            get {
                return ResourceManager.GetString("RecentChatTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll never share your email with anyone else..
        /// </summary>
        public static string RegisterFormEmailDescription {
            get {
                return ResourceManager.GetString("RegisterFormEmailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address:.
        /// </summary>
        public static string RegisterFormEmailLabel {
            get {
                return ResourceManager.GetString("RegisterFormEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        public static string RegisterFormEmailPlaceholder {
            get {
                return ResourceManager.GetString("RegisterFormEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        public static string RegisterFormFirstNameLabel {
            get {
                return ResourceManager.GetString("RegisterFormFirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string RegisterFormFirstNamePlaceholder {
            get {
                return ResourceManager.GetString("RegisterFormFirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        public static string RegisterFormLastNameLabel {
            get {
                return ResourceManager.GetString("RegisterFormLastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string RegisterFormLastNamePlaceholder {
            get {
                return ResourceManager.GetString("RegisterFormLastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string RegisterFormPasswordLabel {
            get {
                return ResourceManager.GetString("RegisterFormPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterFormPasswordPlaceholder {
            get {
                return ResourceManager.GetString("RegisterFormPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string RegisterSubmitButtonContent {
            get {
                return ResourceManager.GetString("RegisterSubmitButtonContent", resourceCulture);
            }
        }
    }
}
